app:
  cls: kaggle_leaderboard.app.Application
  debug: yes
  router:
    cls: aioworkers_aiohttp.router.Router
    swagger_ui: /docs
    version_ui: 3
  resources:
    /v1:
      include: api.yaml
kaggle:
  user: ''
  key: ''
  competition: 'asasssa'
